width = 10 # set the width of the game space
height = 25 # set the height of the game space
screen = []
setScreen = []
piecePos = [1,4]
Piece = ""
PieceRot = "N"
PiecesLst = ["O","I","L","J","Z","S","T"]
PieceQ = []
locking = False
heldPiece = ""